### ISSUE TITLE
odd nodes. may be broken after accepting the pull request

### ISSUE THREAD

**Issue by zeffii** [JuhaW/NodeArrange#4]
I'm not too sure what "Select odd nodes" is supposed to do, but maybe you'd like to confirm if it still works or not -- sorry if it has been broken by the PR.  ( I did say that I preferred the pull request wasn't accepted )

You may wish to revert, and wait until I can provide a better PR.

**Comment by zeffii** [comment]
oh wait.. is 'Select Odd Nodes' supposed to select those nodes that don't connect to another node (and therefor have no effect on the tree? )

**Comment by zeffii** [comment]
in that case ignore this :)

**Comment by JuhaW** [comment]
Hullo, yes, separated  nodes and nodes which have no effect on the tree, 
like missing output nodes.
http://puu.sh/ljWMi/3fce610815.png
