### ISSUE TITLE
Addon not working in 2.79

### ISSUE THREAD

**Issue by cyberlecs** [JuhaW/NodeArrange#7]
Another great addon JuhaW, thank you!
Unfortunately it is not working in 2.79. Could you update it, please?

Also as a feateure request, could you create an option to manually ajust the width and XY location of the active addon, please?
You can already acess this in the Outliner > Datablocks > Nodegroups, but you have to navegate one by one through all the nodes.
![untitled-2](https://user-images.githubusercontent.com/338739/40590631-37bbc80c-61d8-11e8-88c9-57cd455cefcb.jpg)

**Comment by JuhaW** [comment]
You mean adjust width and xy locations of the active node (not addon) ?

**Comment by cyberlecs** [comment]
Yes, the active node.
I find easier to copy-paste nodes across different node trees, if they're arranged consistently.

**Comment by JuhaW** [comment]
Now it should works with Blender v2.79.4

**Comment by cyberlecs** [comment]
Thank you!
