### ISSUE TITLE
Does not work in blender 2.8

### ISSUE THREAD

**Issue by Momongaka** [JuhaW/NodeArrange#8]
Cannot seem to get the script to run. It errors out saying look at the console.

**Comment by hitrpr** [comment]
it is for b2.79
and looks like abandoned.

**Comment by hitrpr** [comment]
it is for b2.79
and looks like abandoned.

**Comment by JuhaW** [comment]
Its included in Blender 2.8+.
https://docs.blender.org/manual/en/dev/addons/node/node_arrange.html
